# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 13:59
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, height_field='height_field', null=True, upload_to=timeline.models.upload_location, width_field='width_field'),
        ),
    ]
