# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
