# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20160124_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
