# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 14:33
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20160125_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(height_field='height_field', null=True, upload_to=timeline.models.upload_location, width_field='width_field'),
        ),
    ]
