# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20160124_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='media',
            name='publish',
        ),
        migrations.AlterField(
            model_name='media',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
