# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20160126_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='desription',
            new_name='description',
        ),
    ]
