# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20160124_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Photo',
        ),
    ]
