# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20160126_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
