# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:42
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import timeline.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20160124_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_rotated',
            field=imagekit.models.fields.ProcessedImageField(default='Choose an image', height_field='height_field', upload_to=timeline.models.upload_location, width_field='width_field'),
        ),
    ]
