# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_auto_20160129_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
