# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0024_auto_20160202_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
